=== Jo-dle/PPF_UF2218_Joel/xml/usuarios.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Tipo personalizado para el rol -->
    <xs:simpleType name="rolType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Administrador"/>
            <xs:enumeration value="Consultor"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Tipo personalizado para email -->
    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@\s]+@[^@\s]+\.[a-zA-Z]{2,}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Tipo personalizado para ID -->
    <xs:simpleType name="idType">
        <xs:restriction base="xs:string">
            <xs:pattern value="ID[0-9]{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Elemento raíz -->
    <xs:element name="usuarios">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuario" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="correo" type="emailType"/>
                            <xs:element name="contraseña" type="xs:string"/>
                            <xs:element name="rol" type="rolType"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="idType" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Jo-dle/PPF_UF2218_Joel/xml/usuarios.xml
<?xml version="1.0" encoding="UTF-8"?>
    <!--Referencia al xsl-->
<?xml-stylesheet type="text/xsl" href="usuarios.xsl"?>
<!--Referencia al xsd para validar la estructura-->
<usuarios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./usuarios.xsd">

    <usuario id="ID001">
        <nombre>Constantino</nombre>
        <correo>lantigua21@gmail.com</correo>
        <contraseña>1234</contraseña>
        <rol>administrador</rol>
    </usuario>

    <usuario id="ID002">
        <nombre>Neftalí</nombre>
        <correo>neftali@gmail.com</correo>
        <contraseña>12345</contraseña>
        <rol>administrador</rol>
    </usuario>

    <usuario id="ID003">
        <nombre>Jose</nombre>
        <correo>jose@gmail.com</correo>
        <contraseña>jose1234</contraseña>
        <rol>consultor</rol>
    </usuario>

    <usuario id="ID004">
        <nombre>Manuel</nombre>
        <correo>manuel@gmail.com</correo>
        <contraseña>manuel1234</contraseña>
        <rol>consultor</rol>
    </usuario>

</usuarios>
